name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: install npm
        shell: bash -l {0}
        run: nvm install

      - name: install dependencies
        run: npm ci

      - name: compile contracts
        run: npm run build

      - name: run unit tests
        run: npm run test