name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        testGroup: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: install npm
        shell: bash -l {0}
        run: nvm install

      - name: install dependencies
        run: npm install

      - name: compile contracts
        run: npm run build

      - name: set test group for mocha grep
        run: echo "MOCHA_GREP=<<# matrix.testGroup >>\[@group=<< matrix.testGroup >>\]<</ matrix.testGroup >>" >> $GITHUB_ENV

      - name: run unit tests
        run: npm run testParallel